# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: idm.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'idm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tidm.proto\".\n\x0b\x41uthRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1d\n\x0c\x41uthResponse\x12\r\n\x05token\x18\x01 \x01(\t\")\n\x18ValidateOrDestroyRequest\x12\r\n\x05token\x18\x01 \x01(\t\"-\n\x10ValidateResponse\x12\x0b\n\x03sub\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"\"\n\x0f\x44\x65stroyResponse\x12\x0f\n\x07success\x18\x01 \x01(\t2\xa4\x01\n\x03Idm\x12+\n\x0c\x41uthenticate\x12\x0c.AuthRequest\x1a\r.AuthResponse\x12\x38\n\x08Validate\x12\x19.ValidateOrDestroyRequest\x1a\x11.ValidateResponse\x12\x36\n\x07\x44\x65stroy\x12\x19.ValidateOrDestroyRequest\x1a\x10.DestroyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=13
  _globals['_AUTHREQUEST']._serialized_end=59
  _globals['_AUTHRESPONSE']._serialized_start=61
  _globals['_AUTHRESPONSE']._serialized_end=90
  _globals['_VALIDATEORDESTROYREQUEST']._serialized_start=92
  _globals['_VALIDATEORDESTROYREQUEST']._serialized_end=133
  _globals['_VALIDATERESPONSE']._serialized_start=135
  _globals['_VALIDATERESPONSE']._serialized_end=180
  _globals['_DESTROYRESPONSE']._serialized_start=182
  _globals['_DESTROYRESPONSE']._serialized_end=216
  _globals['_IDM']._serialized_start=219
  _globals['_IDM']._serialized_end=383
# @@protoc_insertion_point(module_scope)
